# Generated by Django 5.2.17 on 2026-09-18 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Programming Languages'), ('frameworks', 'Frameworks & Tools'), ('systems', 'Systems & Architecture'), ('security', 'Cybersecurity & Networking')], default='languages', max_length=30)),
                ('proficiency_percent', models.IntegerField(default=75)),
                ('is_core', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
