# Generated by Django 5.2.17 on 2026-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
