# Generated by Django 5.2.17 on 2026-09-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Programming Languages'), ('frameworks', 'Frameworks & Tools'), ('systems', 'Systems & Architecture'), ('security', 'Cybersecurity & Networking'), ('others', 'Other')], default='languages', max_length=30),
        ),
    ]
